development:
  sessions:
    default:
      database: test_pop #ophealth-dev3
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: pophealth_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: new_popdev
      hosts:
        - localhost:27017
